apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: raman-micro
  description: Flask microservice demo with Prometheus & Grafana
  tags:
    - flask
    - python
    - prometheus
    - demo
  annotations:
    github.com/project-slug: ramannkhanna2/raman-micro
    backstage.io/techdocs-ref: dir:.
    grafana/dashboard-url: http://54.233.49.51:3001/d/1f416562-37ea-4ef1-8df3-d6d1381b7f89/count?orgId=1&from=now-6h&to=now&timezone=browser
    grafana/dashboard-selector: 'dashboard_title=raman-micro-dashboard'
    grafana/tag-selector: 'service=raman-micro'
spec:
  type: service
  lifecycle: production
  owner: dev-team
  system: raman-platform


